spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaTeamDevelopment
    username: postgres
    password: XnyaoX0502
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update